Agendamiento_Cita = '1fM38qL-ZQZaRznnd_oFOcwGbe9oe30FK0CMkpQFFwIk'
Hora_Inicio = '15b4eZs-E4SDrO4Xncn9Lbez2JiuEDOK1-i1gDfXQsLQ'
Hora_Fin = '1HErTZKbiBCjTLbyDg0oOj18WLd1XcRcGuSJN7ZbEXww'
Servicio = '1Peq-KGoPjpHnbx1m3FU3vkHuJYrUq8_OhN_6IAHn3bk'
Departamento = '17cFgI8VorEUcgMRuLIl3ZOQU_fETc5zouSFQj5Vbj5c'
Programa = '1VjfFmIhu2XIBgSQgkebtjyn6OkBQ-2EeYzvC5OTbDUI'
Grupo_Escolar = '1wULVsDdUaPHxLfj_M_wf8xOcQZdIEKTymsFZS80ZI7A'
Cita = '1-xDxCOOH-JJG79LXduHB_l7-7QLxyeu3j6HzRo4WdkE'
Fecha_Inicio = '1UN7Y4sDLiAlg5t47AA9aIEFdRYBB6wHN-_dEio4w7GU'
Fecha_Fin = '1uJCH-jJ_0ch-kbZILLDBbAWH33n7kM2_vGzXHk7vg9g'
Especialista = '1VhjkDY_C6TlZH7mJnKVZcRBakFMPRpi7HszXWV_HCc0'
Usuario = '10xzTQmuVt8VsKk3YYZrJv0yIA-FI3PUdojstQMnGVMI'
Alumno = '1OHPgxWOuWpSpMZxa_relv09ryWKZKxQt_i4VCLyOL5I'
Acesso = '1A4aTV1qNDf8VDU6GrV3StYsteSpKRMBEtJjWor-AgVE'



Agendamiento_Cita_range = 'Sheet1!A2:K'
Hora_Inicio_range = 'Hoja 1!A2:D'
Hora_Fin_range = 'Hoja 1!A2:D'
Servicio_range = 'Hoja1!A2:D'
Departamento_range = 'Hoja 1!A2:B'
Programa_range = 'Hoja 1!A2:B'
Grupo_Escolar_range = 'Hoja 1!A2:B'
Cita_range = 'Hoja 1!A2:F'
Fecha_Inicio_range = 'Hoja 1!A2:E'
Fecha_Fin_range = 'Hoja 1!A2:E'
Especialista_range = 'Especialistas!A2:E'
Usuario_range = 'Usuarios!A2:E'
Alumno_range = 'Hoja1!A2:K'
Acesso_range = 'Sheet1!A2:C'